#### Render Blueprint specification: https://dashboard.render.com/blueprints ####
## ðŸ‘‡ Preview environments: https://render.com/docs/preview-environments ###
# previewsEnabled: true
## ðŸ‘‡ Automatically nuke the environment after X days of inactivity to reduce billing:
# previewsExpireAfterDays: 2
services:
  - type: web
    name: starter-kit-app
    env: node
    plan: free
    ## ðŸ‘‡ Specify the plan for the PR deployment:
    # previewPlan: starter
    ## ðŸ‘‡ Preview Environment Initialization script:
    # initialDeployHook: bun run db-seed
    buildCommand: bun install && bun run build
    startCommand: bun start
    healthCheckPath: /api/trpc/healthcheck
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: starter-kit-db
          property: connectionString

databases:
  - name: starter-kit-db
    plan: free
