version: "3"

services:
  postgres:
    image: postgres:15.10
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-volume:/var/lib/postgresql-pgboss-test/data

volumes:
  postgres-volume:
